modLoader="javafml"
loaderVersion="[45,)"
license="MIT"

[[mods]] #mandatory
modId="golemchad" #mandatory
version="${file.jarVersion}"
displayName="Golem Chad"
logoFile="golemchad.png"
credits="Golem texture by 'Unavoided' on planet minecraft, Gigachad song by 'Bring Me The Horizon' on youtube."
authors="PhoenixWB"

description='''
Chad up your golems.
'''

[[dependencies.golemchad]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[45,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.golemchad]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"